### ISSUE TITLE
Path configuration files(.pth) are still loaded from user site-packages for jupyterhub.singleuser process

### ISSUE THREAD

**Issue by krishnan-r** [swan-cern/systemuser-image#48]
Python import machinery, has the [site](https://docs.python.org/3/library/site.html) module which configures where to look for packages. The module on import, also loads any `.pth` files in the default paths to `sys.path`.

Due to the way we remove the user site-packages by modifying `sys.path` [here](https://github.com/swan-cern/systemuser-image/blob/aa3827cd13bc7eed4a81af345ecc997bb1120c36/executables/jupyterhub-singleuser#L5) after interpreter startup, path configuration files are still loaded from user site-packages. The `site` module is auto-imported when the interpreter starts, and reads `.pth` files before we remove user site-packages directory from `sys.path`

## Impact
Users who have `.pth` files in their CERNBox, i.e `~/.local/**/site-packages` , can break the dependency resolution for notebook server and fail to spawn a session. However it's not clear how these files are added or if installing specific packages triggers this.

## Potential Solution

- Run jupyterhub-singleuser using the python `-s` [option](https://docs.python.org/3/using/cmdline.html#cmdoption-s) only for the notebook server (not kernel processes) which does not load from the user site-packages. (Not tested)

Support Ticket: [INC2957704](https://cern.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsysparm_query%3Dnumber%3DINC2957704)

**Comment by diocas** [comment]
Can you please test? We had been trying to shield the jupyter process for a while and it looks like this corner case was not considered. If it works, we should push it to prod.
